In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import random
from tensorflow import keras


from tensorflow.keras import layers
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score


from keras.layers import SimpleRNN, Embedding, Dense, LSTM, Dropout
from keras.models import Sequential






In [3]:
from google.colab import files
uploaded = files.upload()


Saving final_dataset (1).csv to final_dataset (1).csv


In [4]:
import io
inputs = pd.read_csv(io.StringIO(uploaded['final_dataset (1).csv'].decode('utf-8')))
inputs.head()
print(len(inputs))

1600


In [5]:
print(len(inputs))
inputs.head()

1600


Decision  Sentiment     hotel  ...   n_count wrd_count lstm
0  deceptive          0    hilton  ...  0.203046         3    0
1   truthful          1      omni  ...  0.239130         4    1
2  deceptive          0    monaco  ...  0.240385         0    0
3   truthful          1     hyatt  ...  0.223602         3    1
4   truthful          1  fairmont  ...  0.290123         9    1

[5 rows x 19 columns]

In [6]:
inputs['Serial_No'] = np.arange(len(inputs))
print (inputs)

       Decision  Sentiment             hotel  ... wrd_count lstm Serial_No
0     deceptive          0            hilton  ...         3    0         0
1      truthful          1              omni  ...         4    1         1
2     deceptive          0            monaco  ...         0    0         2
3      truthful          1             hyatt  ...         3    1         3
4      truthful          1          fairmont  ...         9    1         4
...         ...        ...               ...  ...       ...  ...       ...
1595   truthful          1            hilton  ...         4    0      1595
1596   truthful          1  intercontinental  ...         5    0      1596
1597   truthful          1            conrad  ...         5    1      1597
1598   truthful          1           sofitel  ...         1    1      1598
1599  deceptive          0          hardrock  ...         3    1      1599

[1600 rows x 20 columns]


In [7]:
df2 = inputs.reindex(np.random.permutation(inputs.index))
print(df2)

       Decision  Sentiment          hotel  ... wrd_count lstm Serial_No
1055   truthful          1         palmer  ...         6    1      1055
892    truthful          1         amalfi  ...         1    1       892
1179  deceptive          0  knickerbocker  ...         5    0      1179
262    truthful          1        talbott  ...         3    1       262
759    truthful          1       homewood  ...         2    1       759
...         ...        ...            ...  ...       ...  ...       ...
196   deceptive          0       fairmont  ...         4    0       196
404    truthful          1      swissotel  ...         9    1       404
559   deceptive          0         amalfi  ...         2    0       559
1304   truthful          1         monaco  ...         4    1      1304
150    truthful          1         amalfi  ...         3    1       150

[1600 rows x 20 columns]


Index(['Serial No', 'Decision', 'Sentiment', 'hotel', 'polarity', 'source',
       'text', 'anger', 'fear', 'anticipation', 'trust', 'surprise', 'sadness',
       'joy', 'disgust', 'positive', 'negative', 'n_count', 'wrd_count',
       'lstm'],
      dtype='object')

In [8]:
labels = df2['Decision'].values.tolist()
print(labels)

['truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'truthful', 'deceptive', 'deceptive', 'truthful', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'deceptive', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'truthful', 'truthful', 'deceptive', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthf

In [9]:
labels = np.array([0 if label == "deceptive" else 1 for label in labels])

In [ ]:

#labels = df2['Sentiment'].to_numpy()

In [10]:

print(len(labels))

print(labels)

print(labels.shape)


1600
[1 1 0 ... 0 1 1]
(1600,)


In [ ]:
print(labels)

[0 1 1 ... 0 0 0]


In [11]:
# del df2['Sentiment']
# del df2['Decision']
print(df2)

df3 = df2.copy()



       Decision  Sentiment          hotel  ... wrd_count lstm Serial_No
1055   truthful          1         palmer  ...         6    1      1055
892    truthful          1         amalfi  ...         1    1       892
1179  deceptive          0  knickerbocker  ...         5    0      1179
262    truthful          1        talbott  ...         3    1       262
759    truthful          1       homewood  ...         2    1       759
...         ...        ...            ...  ...       ...  ...       ...
196   deceptive          0       fairmont  ...         4    0       196
404    truthful          1      swissotel  ...         9    1       404
559   deceptive          0         amalfi  ...         2    0       559
1304   truthful          1         monaco  ...         4    1      1304
150    truthful          1         amalfi  ...         3    1       150

[1600 rows x 20 columns]


In [ ]:
df2.columns


Index(['Decision', 'Sentiment', 'hotel', 'polarity', 'source', 'text', 'anger',
       'fear', 'anticipation', 'trust', 'surprise', 'sadness', 'joy',
       'disgust', 'positive', 'negative', 'n_count', 'wrd_count', 'lstm',
       'Serial_No'],
      dtype='object')

In [ ]:
df3.columns

Index(['Decision', 'Sentiment', 'hotel', 'polarity', 'source', 'text', 'anger',
       'fear', 'anticipation', 'trust', 'surprise', 'sadness', 'joy',
       'disgust', 'positive', 'negative', 'n_count', 'wrd_count', 'lstm'],
      dtype='object')

In [12]:
# del df2['Sentiment']
# #del df2['index']
# del df2['Decision']

df2.drop(["Decision","Sentiment","hotel","polarity","source","text"],axis=1,inplace=True)
print(df2)

         anger      fear  anticipation  ...  wrd_count  lstm  Serial_No
1055  0.011450  0.003817      0.038168  ...          6     1       1055
892   0.008547  0.008547      0.025641  ...          1     1        892
1179  0.000000  0.012346      0.024691  ...          5     0       1179
262   0.005814  0.011628      0.017442  ...          3     1        262
759   0.012048  0.024096      0.024096  ...          2     1        759
...        ...       ...           ...  ...        ...   ...        ...
196   0.010101  0.000000      0.020202  ...          4     0        196
404   0.017094  0.008547      0.034188  ...          9     1        404
559   0.000000  0.000000      0.047619  ...          2     0        559
1304  0.023256  0.007752      0.023256  ...          4     1       1304
150   0.003704  0.007407      0.018519  ...          3     1        150

[1600 rows x 14 columns]


In [ ]:
print(df3)

       Decision  Sentiment             hotel  ... wrd_count lstm Serial_No
739    truthful          1          sheraton  ...         3    1       739
395   deceptive          0          sheraton  ...         6    0       395
1467  deceptive          0           allegro  ...         9    0      1467
1178   truthful          1          sheraton  ...         1    1      1178
1578   truthful          1  intercontinental  ...         3    0      1578
...         ...        ...               ...  ...       ...  ...       ...
716    truthful          1            monaco  ...         6    1       716
1218  deceptive          0           affinia  ...         3    0      1218
781    truthful          1            amalfi  ...         5    1       781
157   deceptive          0        ambassador  ...         5    0       157
271   deceptive          0  intercontinental  ...         2    0       271

[1600 rows x 20 columns]


In [13]:
train_x = df2.to_numpy()
print(len(train_x))
a = train_x[0]
print(a)

1600
[1.14503820e-02 3.81679400e-03 3.81679390e-02 4.96183210e-02
 3.05343510e-02 1.52671760e-02 3.43511450e-02 7.63358800e-03
 5.72519080e-02 1.52671760e-02 2.16730038e-01 6.00000000e+00
 1.00000000e+00 1.05500000e+03]


In [14]:
split_frac1 = 0.8

idx1 = int(len(train_x) * split_frac1)
train_x, val_x = train_x[:idx1], train_x[idx1:]
train_y, val_y = labels[:idx1], labels[idx1:]

In [15]:
#print(train_x)
print(len(train_x))
print(len(train_y))
print(len(val_x))
print(len(val_y))

1280
1280
320
320


In [16]:
mod_x = train_x[0][:13]



Slicing training data
**bold text**

In [17]:
mod_x = np.zeros((1280,13))

In [18]:
for i in range(len(train_x)):
  mod_x[i] = train_x[i][:13]

In [ ]:
mod_x

array([[0.00000000e+00, 0.00000000e+00, 3.12500000e-02, ...,
        2.06349206e-01, 3.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.23728810e-02, ...,
        2.08333333e-01, 6.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.76190480e-02, ...,
        2.68456376e-01, 9.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 3.44827590e-02, ...,
        2.06896552e-01, 3.00000000e+00, 1.00000000e+00],
       [9.25925900e-03, 0.00000000e+00, 9.25925900e-03, ...,
        2.01834862e-01, 1.00000000e+00, 0.00000000e+00],
       [4.42477900e-03, 1.32743360e-02, 2.21238940e-02, ...,
        2.42290749e-01, 5.00000000e+00, 0.00000000e+00]])

In [19]:
mod_x[0]

array([1.14503820e-02, 3.81679400e-03, 3.81679390e-02, 4.96183210e-02,
       3.05343510e-02, 1.52671760e-02, 3.43511450e-02, 7.63358800e-03,
       5.72519080e-02, 1.52671760e-02, 2.16730038e-01, 6.00000000e+00,
       1.00000000e+00])

In [20]:
index = val_x[0][13:]
index
#print(str(index[0])[0:index[0].size()-2])

array([74.])

**getting index from testing data** 




In [ ]:
index_test = np.zeros((320,1))
for i in range(len(val_x)):
  index_test[i] = int(val_x[i][13:])
  #print(index_test[i])

index_test.astype(int)

In [31]:
testing_x = np.zeros((320,13))
for i in range(len(val_x)):
  testing_x[i] = val_x[i][:13]

In [ ]:
# clf = LogisticRegression()
# clf.fit(train_x,train_y)
# p = clf.predict(val_x)
# print (accuracy_score(train_y,p))

Basic NN
 

In [32]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(1,activation=tf.nn.sigmoid))


model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

class TestCallback(tf.keras.callbacks.Callback):
    def __init__(self, test_data):
        self.test_data = test_data

    def on_epoch_end(self, epoch, logs={}):
        x, y = self.test_data
        loss, acc = self.model.evaluate(x, y, verbose=0)
        print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))



#model.fit(train_x, train_y, validation_data=(val_x, val_y),epochs=50, callbacks=[TestCallback((val_x,val_y))])



model.fit(mod_x,train_y,epochs=50,batch_size=64,verbose=1)
# _, accuracy = model.evaluate(val_x, val_y)
# print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/50
20/20 [==============================] - 0s 3ms/step - loss: 0.7120 - accuracy: 0.5359
Epoch 2/50
20/20 [==============================] - 0s 3ms/step - loss: 0.6829 - accuracy: 0.5875
Epoch 3/50
20/20 [==============================] - 0s 2ms/step - loss: 0.6457 - accuracy: 0.6727
Epoch 4/50
20/20 [==============================] - 0s 3ms/step - loss: 0.5868 - accuracy: 0.7391
Epoch 5/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5138 - accuracy: 0.7992
Epoch 6/50
20/20 [==============================] - 0s 2ms/step - loss: 0.4201 - accuracy: 0.8641
Epoch 7/50
20/20 [==============================] - 0s 2ms/step - loss: 0.3454 - accuracy: 0.8992
Epoch 8/50
20/20 [==============================] - 0s 2ms/step - loss: 0.3238 - accuracy: 0.9062
Epoch 9/50
20/20 [==============================] - 0s 3ms/step - loss: 0.2703 - accuracy: 0.9359
Epoch 10/50
20/20 [==============================] - 0s 3ms/step - loss: 0.2664 - accuracy: 0.9352
Epoch 11/50
20/20 [

In [33]:

_, accuracy = model.evaluate(testing_x, val_y)
print('Accuracy: %.2f' % (accuracy*100))

10/10 [==============================] - 0s 2ms/step - loss: 0.1294 - accuracy: 0.9719
Accuracy: 97.19


In [34]:
y_preds = model.predict(testing_x)
print(y_preds)
y_preds_classes = model.predict_classes(testing_x)
print(y_preds_classes)

[[0.08978946]
 [0.9520713 ]
 [0.96091026]
 [0.9711955 ]
 [0.9866725 ]
 [0.9684448 ]
 [0.9531178 ]
 [0.95994794]
 [0.94242746]
 [0.06054485]
 [0.0509235 ]
 [0.9587984 ]
 [0.9593843 ]
 [0.95388305]
 [0.01088331]
 [0.9508828 ]
 [0.01514034]
 [0.9444628 ]
 [0.9506354 ]
 [0.95391583]
 [0.95481026]
 [0.94303674]
 [0.05177245]
 [0.06081948]
 [0.05942772]
 [0.9533134 ]
 [0.08484524]
 [0.01780363]
 [0.08566982]
 [0.95157105]
 [0.9745541 ]
 [0.0301952 ]
 [0.95921385]
 [0.9776708 ]
 [0.9508308 ]
 [0.9543798 ]
 [0.96392107]
 [0.07105955]
 [0.01545003]
 [0.95234036]
 [0.95020807]
 [0.97740674]
 [0.03500293]
 [0.02155887]
 [0.05041236]
 [0.07090866]
 [0.96698743]
 [0.04180776]
 [0.93933153]
 [0.954929  ]
 [0.01768218]
 [0.04157934]
 [0.031625  ]
 [0.04710594]
 [0.07245775]
 [0.96929115]
 [0.06994157]
 [0.07049325]
 [0.0461114 ]
 [0.9463304 ]
 [0.95950747]
 [0.97010136]
 [0.06132554]
 [0.07131989]
 [0.06050422]
 [0.95945126]
 [0.952173  ]
 [0.959879  ]
 [0.95717716]
 [0.98675764]
 [0.98628646]
 [0.02

**Showing spam and non spam reviews from testing data**

In [35]:
t_index = index_test.astype(int)
len(t_index)


320

In [36]:
df4 = pd.DataFrame()
for i in range(len(t_index)):
    df4 = df4.append(df3.loc[t_index[i]])


In [37]:
df4.columns

Index(['Decision', 'Sentiment', 'hotel', 'polarity', 'source', 'text', 'anger',
       'fear', 'anticipation', 'trust', 'surprise', 'sadness', 'joy',
       'disgust', 'positive', 'negative', 'n_count', 'wrd_count', 'lstm',
       'Serial_No'],
      dtype='object')

In [38]:
spam_review = pd.DataFrame()
non_spam_review = pd.DataFrame()
for i in range(len(df4)):
  if(y_preds_classes[i]==0):
    spam_review = spam_review.append(df4.iloc[i])
  else:
     non_spam_review = non_spam_review.append(df4.iloc[i]) 

spam_review['text'].to_csv('spam_review.csv')
non_spam_review['text'].to_csv('non_spam_review.csv')

**Non Spam Review**

In [ ]:
non_spam_review = pd.DataFrame()
for i in range(len(df4)):
  if(y_preds_classes[i]==1):
    non_spam_review = non_spam_review.append(df4.iloc[i])

non_spam_review['text'].to_csv('non_spam_review.csv')

In [ ]:
spam_review[spam_review.Sentiment==1.0]

Decision  Sentiment  ...     trust  wrd_count
1306  truthful        1.0  ...  0.017094        5.0
1586  truthful        1.0  ...  0.011494        8.0

[2 rows x 20 columns]

In [ ]:

for i in range(320):
  if(y_preds[i]>=0.5):
    y_preds[i]=1
  else:
    y_preds[i]=0

print(y_preds)

In [ ]:
from sklearn import metrics
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(val_y, y_preds_classes)
print('Accuracy: %f' % accuracy)
print('Test accuracy: {:.2f} %'.format(100*metrics.accuracy_score(val_y,y_preds_classes)))
precision = precision_score(val_y, y_preds_classes)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(val_y, y_preds_classes)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(val_y, y_preds_classes)
print('F1 score: %f' % f1)

Accuracy: 0.943750
Test accuracy: 94.38 %
Precision: 0.968553
Recall: 0.922156
F1 score: 0.944785


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          multiple                  0         
_________________________________________________________________
dense_5 (Dense)              multiple                  896       
_________________________________________________________________
dropout_4 (Dropout)          multiple                  0         
_________________________________________________________________
dense_6 (Dense)              multiple                  4160      
_________________________________________________________________
dropout_5 (Dropout)          multiple                  0         
_________________________________________________________________
dense_7 (Dense)              multiple                  4160      
_________________________________________________________________
dropout_6 (Dropout)          multiple                 