In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import random
from tensorflow import keras


from tensorflow.keras import layers
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score


from keras.layers import SimpleRNN, Embedding, Dense, LSTM, Dropout
from keras.models import Sequential






In [ ]:
!pip list

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving final_dataset (1).csv to final_dataset (1).csv


In [ ]:
import io
inputs = pd.read_csv(io.StringIO(uploaded['final_dataset (1).csv'].decode('utf-8')))
inputs.head()
print(len(inputs))

1600


In [ ]:
inputs = inputs.dropna()
print(len(inputs))
print(inputs)

1600
      Unnamed: 0   Decision  Sentiment  ...   n_count wrd_count lstm
0           1494  deceptive          0  ...  0.203046         3    0
1            855   truthful          1  ...  0.239130         4    1
2           1452  deceptive          0  ...  0.240385         0    0
3            856   truthful          1  ...  0.223602         3    1
4            850   truthful          1  ...  0.290123         9    1
...          ...        ...        ...  ...       ...       ...  ...
1595        1047   truthful          1  ...  0.239521         4    0
1596        1195   truthful          1  ...  0.197740         5    0
1597          37   truthful          1  ...  0.338710         5    1
1598         271   truthful          1  ...  0.404255         1    1
1599         638  deceptive          0  ...  0.242424         3    1

[1600 rows x 20 columns]


AttributeError: ignored

In [ ]:
df2 = inputs.reindex(np.random.permutation(inputs.index))
print(df2)

      Unnamed: 0   Decision  Sentiment  ...   n_count wrd_count lstm
1270         536  deceptive          0  ...  0.266667         7    0
819         1458  deceptive          0  ...  0.231405         4    0
880          735  deceptive          0  ...  0.325000         5    0
1054         582  deceptive          0  ...  0.230769         4    0
143          689  deceptive          0  ...  0.226190         6    0
...          ...        ...        ...  ...       ...       ...  ...
473          142   truthful          1  ...  0.321839         2    1
423          533  deceptive          0  ...  0.244898         8    0
727           63   truthful          1  ...  0.344828         5    1
757           84   truthful          1  ...  0.263959         7    1
536           74   truthful          1  ...  0.346154         4    1

[1600 rows x 20 columns]


In [ ]:
df2.rename(columns = {'Unnamed: 0':"Serial_No"},inplace =True)
df2.columns

Index(['Serial No', 'Decision', 'Sentiment', 'hotel', 'polarity', 'source',
       'text', 'anger', 'fear', 'anticipation', 'trust', 'surprise', 'sadness',
       'joy', 'disgust', 'positive', 'negative', 'n_count', 'wrd_count',
       'lstm'],
      dtype='object')

In [ ]:
df2[df2.Serial_No == 24]

AttributeError: ignored

Index(['hotel', 'polarity', 'source', 'text', 'anger', 'fear', 'anticipation',
       'trust', 'surprise', 'sadness', 'joy', 'disgust', 'positive',
       'negative', 'n_count', 'wrd_count', 'lstm'],
      dtype='object')

In [ ]:
labels = df2['Decision'].values.tolist()
print(labels)

['deceptive', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'truthful', 'truthful', 'truthful', 'deceptive', 'deceptive', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'deceptive', 'truthful', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'deceptive', 'truthful', 'truthful', 'truthful', 'deceptive', 'deceptive', 'deceptive', 'truthful', 'deceptive', 'deceptive', 'decepti

In [ ]:
labels = np.array([0 if label == "deceptive" else 1 for label in labels])

In [ ]:

#labels = df2['Sentiment'].to_numpy()

In [ ]:

print(len(labels))

print(labels)

print(labels.shape)


1600
[0 0 1 ... 1 0 1]
(1600,)


In [ ]:
print(labels)

[0 1 1 ... 1 0 0]


In [ ]:
# del df2['Sentiment']
# del df2['Decision']
print(df2)

df3 = df2.copy()



       Decision  Sentiment          hotel  ...   n_count wrd_count lstm
527   deceptive          0  knickerbocker  ...  0.203704         9    0
230   deceptive          0     ambassador  ...  0.186275         4    0
842    truthful          1         amalfi  ...  0.263736         7    1
66     truthful          1       hardrock  ...  0.264706         9    1
1351  deceptive          0           omni  ...  0.209770        15    0
...         ...        ...            ...  ...       ...       ...  ...
8      truthful          1        affinia  ...  0.253968         1    1
403    truthful          1          james  ...  0.242857         1    1
1451   truthful          1          james  ...  0.244186         0    1
1123  deceptive          0          hyatt  ...  0.221719         4    0
1039   truthful          1          hyatt  ...  0.201258         4    1

[1600 rows x 19 columns]


In [ ]:
df2.columns


Index(['anger', 'fear', 'anticipation', 'trust', 'surprise', 'sadness', 'joy',
       'disgust', 'positive', 'negative', 'n_count', 'wrd_count', 'lstm'],
      dtype='object')

In [ ]:
df3.columns

Index(['Decision', 'Sentiment', 'hotel', 'polarity', 'source', 'text', 'anger',
       'fear', 'anticipation', 'trust', 'surprise', 'sadness', 'joy',
       'disgust', 'positive', 'negative', 'n_count', 'wrd_count', 'lstm'],
      dtype='object')

In [ ]:
# del df2['Sentiment']
# #del df2['index']
# del df2['Decision']

df2.drop(["Decision","Sentiment","hotel","polarity","source","text"],axis=1,inplace=True)
print(df2)

         anger      fear  anticipation  ...   n_count  wrd_count  lstm
527   0.000000  0.000000      0.012500  ...  0.203704          9     0
230   0.000000  0.000000      0.029412  ...  0.186275          4     0
842   0.000000  0.000000      0.021978  ...  0.263736          7     1
66    0.007547  0.003774      0.026415  ...  0.264706          9     1
1351  0.002890  0.005780      0.034682  ...  0.209770         15     0
...        ...       ...           ...  ...       ...        ...   ...
8     0.000000  0.000000      0.000000  ...  0.253968          1     1
403   0.000000  0.000000      0.014706  ...  0.242857          1     1
1451  0.000000  0.000000      0.011905  ...  0.244186          0     1
1123  0.027523  0.032110      0.018349  ...  0.221719          4     0
1039  0.000000  0.006289      0.025157  ...  0.201258          4     1

[1600 rows x 13 columns]


In [ ]:
print(df3)

       Decision  Sentiment             hotel  ...   n_count wrd_count lstm
1197   truthful          1  intercontinental  ...  0.260062         4    1
222    truthful          1        ambassador  ...  0.265734         5    0
733   deceptive          0           allegro  ...  0.212500         3    0
366    truthful          1            palmer  ...  0.330144         5    1
632   deceptive          0          hardrock  ...  0.245283         7    1
...         ...        ...               ...  ...       ...       ...  ...
1442  deceptive          0            hilton  ...  0.201717         9    0
1439  deceptive          0        ambassador  ...  0.168675        13    0
1416  deceptive          0           talbott  ...  0.218430        14    0
110    truthful          1          homewood  ...  0.268293         4    1
949    truthful          1          homewood  ...  0.226667         3    1

[1600 rows x 19 columns]


In [ ]:
train_x = df2.to_numpy()
print(len(train_x))
a = train_x[0]
print(a)

1600
[0.00000000e+00 0.00000000e+00 1.25000000e-02 2.50000000e-02
 6.25000000e-03 0.00000000e+00 1.87500000e-02 0.00000000e+00
 4.37500000e-02 0.00000000e+00 2.03703704e-01 9.00000000e+00
 0.00000000e+00]


In [ ]:
split_frac1 = 0.8

idx1 = int(len(train_x) * split_frac1)
train_x, val_x = train_x[:idx1], train_x[idx1:]
train_y, val_y = labels[:idx1], labels[idx1:]

In [ ]:
#print(train_x)
print(len(train_x))
print(len(train_y))
print(len(val_x))
print(len(val_y))

1280
1280
320
320


In [ ]:
print(val_x[0])


[0.         0.01136364 0.02272727 0.06818182 0.01136364 0.
 0.03409091 0.         0.07954546 0.02272727 0.3258427  5.
 0.        ]


In [ ]:
clf = LogisticRegression()
clf.fit(train_x,train_y)
p = clf.predict(val_x)
print (accuracy_score(train_y,p))

Basic NN
 

In [ ]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(32,activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(rate=0.25))

model.add(tf.keras.layers.Dense(1,activation=tf.nn.sigmoid))


model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

class TestCallback(tf.keras.callbacks.Callback):
    def __init__(self, test_data):
        self.test_data = test_data

    def on_epoch_end(self, epoch, logs={}):
        x, y = self.test_data
        loss, acc = self.model.evaluate(x, y, verbose=0)
        print('\nTesting loss: {}, acc: {}\n'.format(loss, acc))



#model.fit(train_x, train_y, validation_data=(val_x, val_y),epochs=50, callbacks=[TestCallback((val_x,val_y))])



model.fit(train_x,train_y,epochs=50,batch_size=64,verbose=1)
# _, accuracy = model.evaluate(val_x, val_y)
# print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/50
20/20 [==============================] - 0s 3ms/step - loss: 0.7276 - accuracy: 0.4703
Epoch 2/50
20/20 [==============================] - 0s 3ms/step - loss: 0.6916 - accuracy: 0.5469
Epoch 3/50
20/20 [==============================] - 0s 3ms/step - loss: 0.6776 - accuracy: 0.6125
Epoch 4/50
20/20 [==============================] - 0s 4ms/step - loss: 0.6529 - accuracy: 0.6586
Epoch 5/50
20/20 [==============================] - 0s 3ms/step - loss: 0.6306 - accuracy: 0.6820
Epoch 6/50
20/20 [==============================] - 0s 4ms/step - loss: 0.5732 - accuracy: 0.7437
Epoch 7/50
20/20 [==============================] - 0s 3ms/step - loss: 0.5339 - accuracy: 0.7773
Epoch 8/50
20/20 [==============================] - 0s 3ms/step - loss: 0.4748 - accuracy: 0.8398
Epoch 9/50
20/20 [==============================] - 0s 3ms/step - loss: 0.4192 - accuracy: 0.8555
Epoch 10/50
20/20 [==============================] - 0s 3ms/step - loss: 0.3704 - accuracy: 0.8766
Epoch 11/50
20/20 [

In [ ]:

_, accuracy = model.evaluate(val_x, val_y)
print('Accuracy: %.2f' % (accuracy*100))

10/10 [==============================] - 0s 2ms/step - loss: 0.1470 - accuracy: 0.9688
Accuracy: 96.88


In [ ]:
y_preds = model.predict(val_x)
#print(y_preds)
y_preds_classes = model.predict_classes(val_x)
print(y_preds_classes)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[[1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 

In [ ]:

for i in range(320):
  if(y_preds[i]>=0.5):
    y_preds[i]=1
  else:
    y_preds[i]=0

print(y_preds)

In [ ]:
from sklearn import metrics
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(val_y, y_preds_classes)
print('Accuracy: %f' % accuracy)
print('Test accuracy: {:.2f} %'.format(100*metrics.accuracy_score(val_y,y_preds_classes)))
precision = precision_score(val_y, y_preds_classes)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(val_y, y_preds_classes)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(val_y, y_preds_classes)
print('F1 score: %f' % f1)

Accuracy: 0.943750
Test accuracy: 94.38 %
Precision: 0.968553
Recall: 0.922156
F1 score: 0.944785


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          multiple                  0         
_________________________________________________________________
dense_5 (Dense)              multiple                  896       
_________________________________________________________________
dropout_4 (Dropout)          multiple                  0         
_________________________________________________________________
dense_6 (Dense)              multiple                  4160      
_________________________________________________________________
dropout_5 (Dropout)          multiple                  0         
_________________________________________________________________
dense_7 (Dense)              multiple                  4160      
_________________________________________________________________
dropout_6 (Dropout)          multiple                 